### ISSUE TITLE
samples/Payments/Payments/payment-with-flex-token.py

### ISSUE THREAD

**Issue by jfreres** [CyberSource/cybersource-rest-samples-python#44]
Does not work without modifications.
  paymentInformationCardExpirationMonth = str(cc_expiry)[:2]
        paymentInformationCardExpirationYear = str(cc_expiry)[-2:]   
        paymentInformationCard = Ptsv2paymentsPaymentInformationCard(
            expiration_month = paymentInformationCardExpirationMonth,
            expiration_year = paymentInformationCardExpirationYear,

        )

        paymentInformation = Ptsv2paymentsPaymentInformation(
            card = paymentInformationCard.__dict__
        ) 

 requestObj = CreatePaymentRequest(
            client_reference_information = clientReferenceInformation.__dict__,
            processing_information = processingInformation.__dict__,
            payment_information = paymentInformation.__dict__,
            order_information = orderInformation.__dict__,
            token_information = tokenInformation.__dict__
        )

**Comment by raieru** [comment]
Hi, 

Use the last SDK version and it will works. Remember generate a new Transient Token. 

Output: 
% python samples/Payments/Payments/payment-with-flex-token.py

API RESPONSE CODE :  201

API RESPONSE BODY :  {"_links":{"authReversal":{"method":"POST","href":"/pts/v2/payments/6021410629956176403005/reversals"},"self":{"method":"GET","href":"/pts/v2/payments/6021410629956176403005"},"capture":{"method":"POST","href":"/pts/v2/payments/6021410629956176403005/captures"}},"clientReferenceInformation":{"code":"TC50171_3"},"id":"6021410629956176403005","orderInformation":{"amountDetails":{"authorizedAmount":"102.21","currency":"USD"}},"paymentAccountInformation":{"card":{"type":"001"}},"paymentInformation":{"tokenizedCard":{"type":"001"}},"pointOfSaleInformation":{"terminalId":"111111"},"processorInformation":{"approvalCode":"888888","networkTransactionId":"123456789619999","transactionId":"123456789619999","responseCode":"100","avs":{"code":"X","codeRaw":"I1"}},"reconciliationId":"78148007FFZPRK9A","status":"AUTHORIZED","submitTimeUtc":"2020-10-08T07:11:03Z"}

Best Regards
Raziel

**Comment by jfreres** [comment]
Great!  I will add this to my list update and test.  Thanks.

**Comment by jfreres** [comment]
Sorry same error.  Updated to latest release.

{"submitTimeUtc":"2020-10-08T23:28:32Z","status":"INVALID_REQUEST","reason":"MISSING_FIELD","message":"Declined - The request is missing one or more fields","details":[{"field":"paymentInformation.tokenizedCard.expirationMonth","reason":"MISSING_FIELD"},{"field":"paymentInformation.card.expirationYear","reason":"MISSING_FIELD"}]}

**Comment by jfreres** [comment]
Has this been tested against multiple processors 'smartpay' I get responsecode of 100 or a valid one on a other processors 'gpn' 000?  Where is the request information 100 'This was process success'  Here are result differences in the first result of mine capture = true, second if capture = false?
API RESPONSE CODE :  201

API RESPONSE BODY :  {"_links":{"void":{"method":"POST","href":"/pts/v2/payments/6022027019256240104006/voids"},"self":{"method":"GET","href":"/pts/v2/payments/6022027019256240104006"}},"clientReferenceInformation":{"code":"SO674202010051335-2"},"id":"6022027019256240104006","orderInformation":{"amountDetails":{"totalAmount":"7.24","authorizedAmount":"7.24","currency":"USD"}},"paymentAccountInformation":{"card":{"type":"001"}},"paymentInformation":{"accountFeatures":{"category":"A"},"tokenizedCard":{"type":"001"}},"processorInformation":{"approvalCode":"831000","cardVerification":{"resultCode":"3"},"networkTransactionId":"558196000003814","transactionId":"558196000003814","responseCode":"000","avs":{"code":"Y","codeRaw":"Y"}},"status":"AUTHORIZED","submitTimeUtc":"2020-10-09T00:18:22Z","tokenInformation":{"instrumentidentifierNew":false,"instrumentIdentifier":{"state":"ACTIVE","id":"7010000000148581111"},"shippingAddress":{"id":"B132B890D4899E00E05341588E0A0DFC"},"paymentInstrument":{"id":"B132B890D4869E00E05341588E0A0DFC"},"customer":{"id":"B132B890D4819E00E05341588E0A0DFC"}}}

API RESPONSE CODE :  201

API RESPONSE BODY :  {"_links":{"authReversal":{"method":"POST","href":"/pts/v2/payments/6022500611146258803002/reversals"},"self":{"method":"GET","href":"/pts/v2/payments/6022500611146258803002"},"capture":{"method":"POST","href":"/pts/v2/payments/6022500611146258803002/captures"}},"clientReferenceInformation":{"code":"SO674202010051335-2"},"id":"6022500611146258803002","orderInformation":{"amountDetails":{"authorizedAmount":"7.24","currency":"USD"}},"paymentAccountInformation":{"card":{"type":"001"}},"paymentInformation":{"accountFeatures":{"category":"A"},"tokenizedCard":{"type":"001"}},"processorInformation":{"approvalCode":"831000","cardVerification":{"resultCode":"3"},"networkTransactionId":"558196000003814","transactionId":"558196000003814","responseCode":"000","avs":{"code":"Y","codeRaw":"Y"}},"status":"AUTHORIZED","submitTimeUtc":"2020-10-09T13:27:41Z","tokenInformation":{"instrumentidentifierNew":false,"instrumentIdentifier":{"state":"ACTIVE","id":"7010000000148581111"},"shippingAddress":{"id":"B13DE832EF7D1AA1E05340588D0A6A5A"},"paymentInstrument":{"id":"B13DE4CC55CE18CFE05340588D0A42AC"},"customer":{"id":"B13DE832EF7A1AA1E05340588D0A6A5A"}}}

**Comment by jfreres** [comment]
Reproducible on the developer site changing to Global Processor?

 "processorInformation": {
        "approvalCode": "831000",
        "networkTransactionId": "558196000003814",
        "transactionId": "558196000003814",
        "responseCode": "000",
        "avs": {
            "code": "Y",
            "codeRaw": "Y"
        }
    },

**Comment by raieru** [comment]
Hi,

So, Is all good now?

Raziel

**Comment by jfreres** [comment]
No.  If the processor is set to GPN the responseCode is 000 the only indicator is Authorized?  Why not return the request information just like smartpay?  I still have to pass the cardexp month, year as a payment object to the request in either processor mode smartpay or GPN.

**Comment by jfreres** [comment]
This is fixed this issue was the transient token in did not contain these values:
{"submitTimeUtc":"2020-10-08T23:28:32Z","status":"INVALID_REQUEST","reason":"MISSING_FIELD","message":"Declined - The request is missing one or more fields","details":[{"field":"paymentInformation.tokenizedCard.expirationMonth","reason":"MISSING_FIELD"},{"field":"paymentInformation.card.expirationYear","reason":"MISSING_FIELD"}]}

In the options variable of the Javascript form post the scoping of these variables was not populating values.
